management:
  security:
    enabled: false
  info:
    git:
      enabled: true
  health:
    diskspace:
      enabled: false
security:
  basic:
    enabled: true
  user:
    name: admin
    password: ch0colateCak3
logging:
  level:
    org.springframework: INFO